name = "cdsp-lean"
version = "0.1.0"
keywords = ["logic", "distributed systems", "cross-domain", "atomicity"]
defaultTargets = ["mlda", "CDSP"]

[leanOptions]
pp.unicode.fun = true
pp.fieldNotation = false
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"

[[lean_lib]]
name = "mlda"

[[lean_lib]]
name = "CDSP"
